core/rest_api/urls.py
from django.urls import path, include
from rest_framework import routers

import core.rest_api.views as views

router = routers.SimpleRouter()

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
    path(
        "current_hitlist/",
        views.CurrentHitListView.as_view(),
        name="current-hitlist",
    ),
    path("api/search/", views.SpotipySearchView.as_view(), name="search"),
    path(
        "api/get/<str:spotifyuri>",
        views.SpotipyGetView.as_view(),
        name="get",
    ),
    path("api/stats/", views.TrackStatsGetView.as_view(), name="track-stats"),
]

core/urls.py
from django.urls import path


import core.views.dashboard as dashboard_views
import core.views.voting as voting_views


app_name = "core"
urlpatterns = [
    path("", voting_views.IndexView.as_view(), name="index"),
    path("closed/", voting_views.HitlistClosedView.as_view(), name="closed"),
    path("stemmen/", voting_views.VoteView.as_view(), name="vote"),
    path(
        "stem/<uuid:pk>",
        voting_views.VoteSubmissionDetailView.as_view(),
        name="vote-submission-detail",
    ),
    path(
        "eigen-nummer-toegevoegen/",
        voting_views.AddCustomTrackView.as_view(),
        name="add-custom-track",
    ),
    path(
        "eigen-nummer-is-toegevoegd/",
        voting_views.AddCustomTrackSuccessView.as_view(),
        name="add-custom-track-success",
    ),
    path(
        "dashboard/", dashboard_views.DashboardView.as_view(), name="dashboard"
    ),
    path(
        "dashboard/cms/hitlist",
        dashboard_views.HistListListView.as_view(),
        name="hitlist-list",
    ),
    path(
        "dashboard/cms/hitlist/create",
        dashboard_views.HitListCreateView.as_view(),
        name="hitlist-create",
    ),
    path(
        "dashboard/cms/hitlist/update/<str:pk>",
        dashboard_views.HitListUpdateView.as_view(),
        name="hitlist-update",
    ),
    path(
        "dashboard/cms/hitlist/delete/<str:pk>",
        dashboard_views.HitListDeleteView.as_view(),
        name="hitlist-delete",
    ),
    path(
        "dashboard/cms/hitlist/export/<str:pk>",
        dashboard_views.HitListExportView.as_view(),
        name="hitlist-export",
    ),
    path(
        "dashboard/cms/similar-tracks",
        dashboard_views.SimilarTrackView.as_view(),
        name="similar-track-list",
    ),
    path(
        "dashboard/cms/custom-track",
        dashboard_views.CustomTrackListView.as_view(),
        name="custom-track-list",
    ),
    path(
        "dashboard/cms/custom-track/update/<str:pk>",
        dashboard_views.CustomTrackUpdateView.as_view(),
        name="custom-track-update",
    ),
    path(
        "dashboard/cms/merge-tracks",
        dashboard_views.MergeTracksView.as_view(),
        name="merge-tracks",
    ),
    path(
        "dashboard/cms/toggle-submission-invalidation/<str:votesubmissionid>",
        dashboard_views.ToggleSubmissionInvalidation.as_view(),
        name="toggle-submission-invalidation",
    ),
    path(
        "dashboard/create-spotify-playlist/<str:hitlist_id>",
        dashboard_views.HitListCreateSpotifyPlaylistView.as_view(),
        name="create-spotify-playlist",
    ),
    path(
        "dashboard/spotify-oauth",
        dashboard_views.SpotifyOAuthView.as_view(),
        name="spotify-oauth",
    ),
]

popell_top100/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("api/", include("core.rest_api.urls")),
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("accounts/login/", LoginView.as_view()),
]

core/rest_api/views.py
from rest_framework import generics
from dataclasses import asdict

from core.models.music import Track
from core.models.voting import HitList, Vote, VoteSubmission
from core.rest_api.serializers import HitListSerializer
from core.services.settings import SettingsService
from rest_framework.views import APIView
from rest_framework.response import Response

from core.services.voting import HitListService
from core.spotify import spotify
from rest_framework import status
from rest_framework import permissions


class CurrentHitListView(generics.RetrieveAPIView):
    serializer_class = HitListSerializer

    def get_object(self):
        return SettingsService.get_current_hitlist(self.request)

    def get_queryset(self):
        return HitList.objects.all()


class SpotipySearchView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        q = request.GET.get("q")
        search_results = spotify.search_custom_tracks(
            q
        ) + spotify.search_tracks(q)
        return Response({"results": [asdict(x) for x in search_results]})


class SpotipyGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, spotifyuri, format=None):
        return Response(asdict(spotify.get_track_by_uri(spotifyuri)))


class TrackStatsGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        title = request.GET.get("title", "")
        year = request.GET.get("year", "")
        artist = request.GET.get("artist", "")
        track_uri = request.GET.get("spotify_uri", "")
        print(title, year, artist, track_uri)
        hitlist = HitListService.get_by_year(year)
        track = Track.find_by_uri_or_title(track_uri, title)
        if track is None:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not found!"},
            )
        votes = Vote.objects.filter(
            track=track,
            submission__hit_list=hitlist,
            submission__is_invalidated=False,
        )
        if votes.count() == 0:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not part of hitlist!"},
            )
        position = 1
        for entry in hitlist.get_list():
            if entry.id == track.id:
                break
            position += 1
        vote_count, points = 0, 0
        for vote in votes:
            vote_count += 1
            points += vote.points
        votes = VoteSubmission.objects.filter(
            hit_list=hitlist, vote__track=track, is_invalidated=False
        ).values("submitter_name")
        return Response(
            {
                "track": str(track),
                "position": position,
                "points": points,
                "number_of_votes": vote_count,
                "voters": list(votes),
            }
        )

core/views/dashboard.py
import logging
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    FormView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from core.forms import MergeTracksForm
from core.models.music import Track
from core.models.voting import HitList, VoteSubmission
from core.services.music import SimilarTrackService
from core.services.settings import SettingsService
from core.services.voting import HitListService
from core.spotify import spotify
from core.widgets import CustomDateTimeInput
from tinymce.widgets import TinyMCE  # type: ignore

HITLIST_LIST_URL = "core:hitlist-list"
DASHBOARD_URL = "core:dashboard"


logger = logging.getLogger(__name__)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        if "list" in request.GET:
            hitlist = get_object_or_404(HitList, id=request.GET["list"])
            SettingsService.set_current_hitlist(request, hitlist)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["hitlists"] = HitList.objects.all()
        ctx["hitlist"] = SettingsService.get_current_hitlist(self.request)
        ctx["vote_count"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=False
        ).count()
        ctx["invalidated"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=True
        ).count()
        return ctx


class HistListListView(LoginRequiredMixin, ListView):
    model = HitList
    template_name = "dashboard/cms/hitlistlist.html"


class SimilarTrackView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/cms/similartracks.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["similar_tracks"] = SimilarTrackService.get_similar_tracks()
        return ctx


class HitListCreateView(LoginRequiredMixin, CreateView):
    model = HitList
    template_name = "dashboard/cms/hitlistcreate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListUpdateView(LoginRequiredMixin, UpdateView):
    model = HitList
    template_name = "dashboard/cms/hitlistupdate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
        "is_closed",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListDeleteView(LoginRequiredMixin, DeleteView):
    model = HitList
    success_url = reverse_lazy(HITLIST_LIST_URL)
    template_name = "dashboard/cms/hitlistdelete.html"


class HitListExportView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=pk)
        return HitListService.export_to_excel(hitlist)


class CustomTrackListView(LoginRequiredMixin, ListView):
    model = Track
    template_name = "dashboard/cms/tracklist.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_related("artists")
            .filter(is_non_spotify=True)
        )


class CustomTrackUpdateView(LoginRequiredMixin, UpdateView):
    model = Track
    template_name = "dashboard/cms/trackupdate.html"
    fields = ["title", "artists", "preview_url", "image_url"]
    success_url = reverse_lazy("core:custom-track-list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["artists"].queryset = form.fields[
            "artists"
        ].queryset.filter(is_non_spotify=True)
        return form


class MergeTracksView(LoginRequiredMixin, FormView):
    form_class = MergeTracksForm
    template_name = "dashboard/cms/mergetracks.html"
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ToggleSubmissionInvalidation(LoginRequiredMixin, View):
    def get(self, request, votesubmissionid, *args, **kwargs):
        submission = VoteSubmission.objects.get(id=votesubmissionid)
        submission.is_invalidated = not submission.is_invalidated
        submission.save()
        return redirect(reverse_lazy(DASHBOARD_URL))


class HitListCreateSpotifyPlaylistView(View):
    def get(self, request, hitlist_id, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=hitlist_id)
        try:
            HitListService.create_spotify_list(
                hitlist, request.session.get("spotify_token")
            )
        except Exception as e:
            logger.error("Failed to create spotify playlist!")
            logger.error(e)
            request.session["spotify_token"] = None
        return redirect(reverse_lazy(DASHBOARD_URL))


class SpotifyOAuthView(View):
    def get(self, request):
        spotify_oauth = spotify.get_spotify_oauth()
        callback_code = request.GET.get("code", None)
        if callback_code:
            # Found callback code, add access token to session
            access_token = spotify_oauth.get_access_token(callback_code)[
                "access_token"
            ]
            request.session["spotify_token"] = access_token
            return redirect(reverse_lazy(DASHBOARD_URL))
        else:
            return redirect(spotify_oauth.get_authorize_url())

core/views/mixins.py
from django.shortcuts import redirect
from django.views import View

from core.services.voting import HitListService


class OpenHitListRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if (
            not HitListService.get_current_hitlist()
            or HitListService.get_current_hitlist().is_closed
        ):
            return redirect("core:closed")
        return super().dispatch(request, *args, **kwargs)

core/views/voting.py
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from core.forms import CustomTrackForm, VoteSubmissionForm
from core.models.voting import VoteSubmission
from core.services.settings import SettingsService
from core.services.voting import HitListService
from core.views.mixins import OpenHitListRequiredMixin

from django.views.generic import TemplateView, DetailView, FormView
from django.utils.translation import activate


class IndexView(OpenHitListRequiredMixin, TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["hitlist"] = HitListService.get_current_hitlist()
        return context


class HitlistClosedView(TemplateView):
    template_name = "closed.html"


class VoteView(OpenHitListRequiredMixin, View):
    template_name = "vote.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            self.template_name,
            {
                "voteForm": VoteSubmissionForm(),
                "hitlist": HitListService.get_current_hitlist(),
            },
        )

    def post(self, request, *args, **kwargs):
        activate("nl")  # Make sure errors are displayed in correct language
        form = VoteSubmissionForm(request.POST)
        if (
            form.is_valid()
        ):  # Valid submission, save and redirect to detail page
            vote_submission = form.save()
            return redirect(
                reverse(
                    "core:vote-submission-detail",
                    kwargs={"pk": vote_submission.id},
                )
            )
        return render(
            request,
            self.template_name,
            {
                "voteForm": form,
                "hitlist": HitListService.get_current_hitlist(),
            },
        )


class VoteSubmissionDetailView(DetailView):
    template_name = "view_vote_submission.html"
    model = VoteSubmission

    def get_queryset(self):
        return (
            super().get_queryset().prefetch_related("vote_set__track__artists")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vote = self.get_object()
        context["hitlist"] = vote.hit_list
        return context


class AddCustomTrackView(FormView):
    form_class = CustomTrackForm
    template_name = "add_custom_song.html"
    success_url = reverse_lazy("core:add-custom-track-success")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["hitlist"] = HitListService.get_current_hitlist()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class AddCustomTrackSuccessView(TemplateView):
    template_name = "add_custom_song_success.html"

core/templates/dashboard/cms/hitlistcreate.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>Nieuwe lijst aanmaken</h1>
{% endblock %}
{% block head %}
    {{ form.media }}
{% endblock %}
{% block content %}
    <div class="card">
        <form method="post">
            {% csrf_token %}
            <div class="card-body">
                {{ form | crispy }}

            </div>
            <div class="card-footer text-end">
                <div class="d-flex">
                    <a href="{% url "core:hitlist-list" %}" class="btn btn-link">Annuleren</a>
                    <button type="submit" class="btn btn-primary ms-auto">Aanmaken</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/dashboard/cms/hitlistdelete.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>{{ object.name }} verwijderen?</h1>
{% endblock %}
{% block content %}
    <div class="card">
        <form method="post">
            {% csrf_token %}
            <div class="card-footer text-end">
                <div class="d-flex">
                    <a href="{% url "core:hitlist-list" %}" class="btn btn-link">Annuleren</a>
                    <button type="submit" class="btn btn-danger ms-auto">Verwijderen</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/dashboard/cms/hitlistlist.html
{% extends 'dashboard/base.html' %}
{% block title %}
    <h1>Top 100 lijsten</h1>
{% endblock %}
{% block content %}
    <div class="card">
        <div class="table-responsive">
            <table class="table table-vcenter table-mobile-md card-table">
                <caption>Top 100 lijsten</caption>
                <tr>
                    <th>Naam</th>
                    <th>Stembus geopend</th>
                    <th>Stembus gesloten</th>
                    <th>Is gesloten?</th>
                    <th><a href="{% url "core:hitlist-create" %}" class="btn btn-success">+</a></th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.name }}</td>
                        <td>{{ object.vote_start_date }}</td>
                        <td>{{ object.vote_end_date }}</td>
                        <td>{% if object.is_closed %}Ja{% else %}Nee{% endif %}</td>
                        <td>
                            <a href="{% url "core:hitlist-export" object.pk %}" class="btn btn-primary">Exporteren</a>
                            <a href="{% url "core:hitlist-update" object.pk %}" class="btn btn-warning">Bewerken</a>
                            <a href="{% url "core:hitlist-delete" object.pk %}" class="btn btn-danger">Verwijderen</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">
                            <h3>Nog geen lijsten aangemaakt</h3>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

core/templates/dashboard/cms/hitlistupdate.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>{{ self.object.name }} bewerken</h1>
{% endblock %}
{% block head %}
    {{ form.media }}
{% endblock %}
{% block content %}
    <div class="card">
        <form method="post">
            {% csrf_token %}
            <div class="card-body">
                {{ form | crispy }}
            </div>
            <div class="card-footer text-end">
                <div class="d-flex">
                    <a href="{% url "core:hitlist-list" %}" class="btn btn-link">Annuleren</a>
                    <button type="submit" class="btn btn-primary ms-auto">Aanpassen</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/dashboard/cms/mergetracks.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_filters %}
{% block head %}
    {{ form.media.css }}
    <style>
        .select2-results__option {color: black!important;}
    </style>
{% endblock %}
{% block title %}
    <h1>Nummers samenvoegen</h1>
{% endblock %}
{% block content %}
    <div class="card">
        <form method="post">
            {% csrf_token %}
            <div class="card-body">
                {{ form | crispy }}
            </div>
            <div class="card-footer text-end">
                <div class="d-flex">
                    <a href="{% url "core:dashboard" %}" class="btn btn-link">Annuleren</a>
                    <button type="submit" class="btn btn-primary ms-auto">Aanpassen</button>
                </div>
            </div>
        </form>
    </div>
    {# Load jQuery #}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    {{ form.media.js }}
{% endblock %}

core/templates/dashboard/cms/similartracks.html
{% extends 'dashboard/base.html' %}
{% block title %}
    <h1>Top 100 lijsten</h1>
{% endblock %}
{% block content %}
    <div class="card">
        {% for match in similar_tracks %}
            <p>{{ match }}</p>
        {% endfor %}
    </div>
{% endblock %}

core/templates/dashboard/cms/tracklist.html
{% extends 'dashboard/base.html' %}
{% load core_extras %}
{% block title %}
    <h1>Eigen nummers</h1>
{% endblock %}
{% block content %}
    <div class="card">
        <div class="table-responsive">
            <table class="table table-vcenter table-mobile-md card-table">
            <caption>Eigen nummers</caption>
                <tr>
                    <th>Titel</th>
                    <th>Artiest</th>
                    <th>Preview URL</th>
                    <th>Afbeelding URL</th>
                    <th>Acties</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.title }}</td>
                        <td>{{ object.artists.all | artist_list }}</td>
                        <td>{{ object.preview_url }}</td>
                        <td>{{ object.image_url }}</td>
                        <td>
                            <a href="{% url 'core:custom-track-update' object.id %}" class="btn btn-warning">Bewerken</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">
                            <h3>Nog geen eigen nummers aangemaakt</h3>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

core/templates/dashboard/cms/trackupdate.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_filters %}
{% block title %}
    <h1>{{ self.object.name }} bewerken</h1>
{% endblock %}
{% block content %}
    <div class="card">
        <form method="post">
            {% csrf_token %}
            <div class="card-body">
                {{ form | crispy }}
            </div>
            <div class="card-footer text-end">
                <div class="d-flex">
                    <a href="{% url "core:custom-track-list" %}" class="btn btn-link">Annuleren</a>
                    <button type="submit" class="btn btn-primary ms-auto">Aanpassen</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}