core/rest_api/urls.py
from django.urls import path, include
from rest_framework import routers

import core.rest_api.views as views

router = routers.SimpleRouter()

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
    path(
        "current_hitlist/",
        views.CurrentHitListView.as_view(),
        name="current-hitlist",
    ),
    path("api/search/", views.SpotipySearchView.as_view(), name="search"),
    path(
        "api/get/<str:spotifyuri>",
        views.SpotipyGetView.as_view(),
        name="get",
    ),
    path("api/stats/", views.TrackStatsGetView.as_view(), name="track-stats"),
]

core/urls.py
from django.urls import path


import core.views.dashboard as dashboard_views
import core.views.voting as voting_views


app_name = "core"
urlpatterns = [
    path("", voting_views.IndexView.as_view(), name="index"),
    path("closed/", voting_views.HitlistClosedView.as_view(), name="closed"),
    path("stemmen/", voting_views.VoteView.as_view(), name="vote"),
    path(
        "stem/<uuid:pk>",
        voting_views.VoteSubmissionDetailView.as_view(),
        name="vote-submission-detail",
    ),
    path(
        "eigen-nummer-toegevoegen/",
        voting_views.AddCustomTrackView.as_view(),
        name="add-custom-track",
    ),
    path(
        "eigen-nummer-is-toegevoegd/",
        voting_views.AddCustomTrackSuccessView.as_view(),
        name="add-custom-track-success",
    ),
    path(
        "dashboard/", dashboard_views.DashboardView.as_view(), name="dashboard"
    ),
    path(
        "dashboard/cms/hitlist",
        dashboard_views.HistListListView.as_view(),
        name="hitlist-list",
    ),
    path(
        "dashboard/cms/hitlist/create",
        dashboard_views.HitListCreateView.as_view(),
        name="hitlist-create",
    ),
    path(
        "dashboard/cms/hitlist/update/<str:pk>",
        dashboard_views.HitListUpdateView.as_view(),
        name="hitlist-update",
    ),
    path(
        "dashboard/cms/hitlist/delete/<str:pk>",
        dashboard_views.HitListDeleteView.as_view(),
        name="hitlist-delete",
    ),
    path(
        "dashboard/cms/hitlist/export/<str:pk>",
        dashboard_views.HitListExportView.as_view(),
        name="hitlist-export",
    ),
    path(
        "dashboard/cms/similar-tracks",
        dashboard_views.SimilarTrackView.as_view(),
        name="similar-track-list",
    ),
    path(
        "dashboard/cms/custom-track",
        dashboard_views.CustomTrackListView.as_view(),
        name="custom-track-list",
    ),
    path(
        "dashboard/cms/custom-track/update/<str:pk>",
        dashboard_views.CustomTrackUpdateView.as_view(),
        name="custom-track-update",
    ),
    path(
        "dashboard/cms/merge-tracks",
        dashboard_views.MergeTracksView.as_view(),
        name="merge-tracks",
    ),
    path(
        "dashboard/cms/toggle-submission-invalidation/<str:votesubmissionid>",
        dashboard_views.ToggleSubmissionInvalidation.as_view(),
        name="toggle-submission-invalidation",
    ),
    path(
        "dashboard/create-spotify-playlist/<str:hitlist_id>",
        dashboard_views.HitListCreateSpotifyPlaylistView.as_view(),
        name="create-spotify-playlist",
    ),
    path(
        "dashboard/spotify-oauth",
        dashboard_views.SpotifyOAuthView.as_view(),
        name="spotify-oauth",
    ),
]

popell_top100/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("api/", include("core.rest_api.urls")),
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("accounts/login/", LoginView.as_view()),
]

core/models/voting.py
import datetime
import uuid

from django.db import models
from django.db.models import Count, Sum, Min

from core.models.music import Track


class HitList(models.Model):
    THEME_CHOICES = (("rock", "Rock"), ("carnaval", "Carnaval"))

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(
        max_length=255, blank=False, null=False, unique=True
    )
    vote_start_date = models.DateTimeField(blank=False, null=False)
    vote_end_date = models.DateTimeField(blank=False, null=False)
    is_closed = models.BooleanField(default=False)
    description = models.TextField(blank=False, null=False, default="")
    theme = models.CharField(
        max_length=255, choices=THEME_CHOICES, default="rock"
    )

    def get_list(self):
        return (
            Track.objects.filter(
                vote__submission__hit_list=self,
                vote__submission__is_invalidated=False,
            )
            .annotate(
                votes=Count("vote__points"),
                score=Sum("vote__points"),
                first_vote=Min("vote__submission__timestamp"),
            )
            .order_by("-score", "-votes", "first_vote")
            .prefetch_related("artists")
        )


class VoteSubmission(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    submitter_name = models.CharField(max_length=255, blank=False, null=False)
    is_invalidated = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    hit_list = models.ForeignKey(
        HitList, blank=False, null=False, on_delete=models.PROTECT
    )

    def __str__(self):
        return self.submitter_name


class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    track = models.ForeignKey(
        Track, blank=False, null=False, on_delete=models.PROTECT
    )
    submission = models.ForeignKey(
        VoteSubmission, blank=False, null=False, on_delete=models.CASCADE
    )
    points = models.PositiveIntegerField(blank=False, null=False)

core/rest_api/views.py
from rest_framework import generics
from dataclasses import asdict

from core.models.music import Track
from core.models.voting import HitList, Vote, VoteSubmission
from core.rest_api.serializers import HitListSerializer
from core.services.settings import SettingsService
from rest_framework.views import APIView
from rest_framework.response import Response

from core.services.voting import HitListService
from core.spotify import spotify
from rest_framework import status
from rest_framework import permissions


class CurrentHitListView(generics.RetrieveAPIView):
    serializer_class = HitListSerializer

    def get_object(self):
        return SettingsService.get_current_hitlist(self.request)

    def get_queryset(self):
        return HitList.objects.all()


class SpotipySearchView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        q = request.GET.get("q")
        search_results = spotify.search_custom_tracks(
            q
        ) + spotify.search_tracks(q)
        return Response({"results": [asdict(x) for x in search_results]})


class SpotipyGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, spotifyuri, format=None):
        return Response(asdict(spotify.get_track_by_uri(spotifyuri)))


class TrackStatsGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        title = request.GET.get("title", "")
        year = request.GET.get("year", "")
        artist = request.GET.get("artist", "")
        track_uri = request.GET.get("spotify_uri", "")
        print(title, year, artist, track_uri)
        hitlist = HitListService.get_by_year(year)
        track = Track.find_by_uri_or_title(track_uri, title)
        if track is None:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not found!"},
            )
        votes = Vote.objects.filter(
            track=track,
            submission__hit_list=hitlist,
            submission__is_invalidated=False,
        )
        if votes.count() == 0:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not part of hitlist!"},
            )
        position = 1
        for entry in hitlist.get_list():
            if entry.id == track.id:
                break
            position += 1
        vote_count, points = 0, 0
        for vote in votes:
            vote_count += 1
            points += vote.points
        votes = VoteSubmission.objects.filter(
            hit_list=hitlist, vote__track=track, is_invalidated=False
        ).values("submitter_name")
        return Response(
            {
                "track": str(track),
                "position": position,
                "points": points,
                "number_of_votes": vote_count,
                "voters": list(votes),
            }
        )

core/views/dashboard.py
import logging
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    FormView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from core.forms import MergeTracksForm
from core.models.music import Track
from core.models.voting import HitList, VoteSubmission
from core.services.music import SimilarTrackService
from core.services.settings import SettingsService
from core.services.voting import HitListService
from core.spotify import spotify
from core.widgets import CustomDateTimeInput
from tinymce.widgets import TinyMCE  # type: ignore

HITLIST_LIST_URL = "core:hitlist-list"
DASHBOARD_URL = "core:dashboard"


logger = logging.getLogger(__name__)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        if "list" in request.GET:
            hitlist = get_object_or_404(HitList, id=request.GET["list"])
            SettingsService.set_current_hitlist(request, hitlist)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["hitlists"] = HitList.objects.all()
        ctx["hitlist"] = SettingsService.get_current_hitlist(self.request)
        ctx["vote_count"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=False
        ).count()
        ctx["invalidated"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=True
        ).count()
        return ctx


class HistListListView(LoginRequiredMixin, ListView):
    model = HitList
    template_name = "dashboard/cms/hitlistlist.html"


class SimilarTrackView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/cms/similartracks.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["similar_tracks"] = SimilarTrackService.get_similar_tracks()
        return ctx


class HitListCreateView(LoginRequiredMixin, CreateView):
    model = HitList
    template_name = "dashboard/cms/hitlistcreate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListUpdateView(LoginRequiredMixin, UpdateView):
    model = HitList
    template_name = "dashboard/cms/hitlistupdate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
        "is_closed",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListDeleteView(LoginRequiredMixin, DeleteView):
    model = HitList
    success_url = reverse_lazy(HITLIST_LIST_URL)
    template_name = "dashboard/cms/hitlistdelete.html"


class HitListExportView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=pk)
        return HitListService.export_to_excel(hitlist)


class CustomTrackListView(LoginRequiredMixin, ListView):
    model = Track
    template_name = "dashboard/cms/tracklist.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_related("artists")
            .filter(is_non_spotify=True)
        )


class CustomTrackUpdateView(LoginRequiredMixin, UpdateView):
    model = Track
    template_name = "dashboard/cms/trackupdate.html"
    fields = ["title", "artists", "preview_url", "image_url"]
    success_url = reverse_lazy("core:custom-track-list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["artists"].queryset = form.fields[
            "artists"
        ].queryset.filter(is_non_spotify=True)
        return form


class MergeTracksView(LoginRequiredMixin, FormView):
    form_class = MergeTracksForm
    template_name = "dashboard/cms/mergetracks.html"
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ToggleSubmissionInvalidation(LoginRequiredMixin, View):
    def get(self, request, votesubmissionid, *args, **kwargs):
        submission = VoteSubmission.objects.get(id=votesubmissionid)
        submission.is_invalidated = not submission.is_invalidated
        submission.save()
        return redirect(reverse_lazy(DASHBOARD_URL))


class HitListCreateSpotifyPlaylistView(View):
    def get(self, request, hitlist_id, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=hitlist_id)
        try:
            HitListService.create_spotify_list(
                hitlist, request.session.get("spotify_token")
            )
        except Exception as e:
            logger.error("Failed to create spotify playlist!")
            logger.error(e)
            request.session["spotify_token"] = None
        return redirect(reverse_lazy(DASHBOARD_URL))


class SpotifyOAuthView(View):
    def get(self, request):
        spotify_oauth = spotify.get_spotify_oauth()
        callback_code = request.GET.get("code", None)
        if callback_code:
            # Found callback code, add access token to session
            access_token = spotify_oauth.get_access_token(callback_code)[
                "access_token"
            ]
            request.session["spotify_token"] = access_token
            return redirect(reverse_lazy(DASHBOARD_URL))
        else:
            return redirect(spotify_oauth.get_authorize_url())

core/views/mixins.py
from django.shortcuts import redirect
from django.views import View

from core.services.voting import HitListService


class OpenHitListRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if (
            not HitListService.get_current_hitlist()
            or HitListService.get_current_hitlist().is_closed
        ):
            return redirect("core:closed")
        return super().dispatch(request, *args, **kwargs)

core/templates/add_custom_song.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}{{ hitlist.name }}{% endblock %}
{% block content %}
    <h1>Eigen nummer toevoegen</h1>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <a href="javascript:close();" class="btn btn-popell">Annuleren</a>
        <button type="submit" class="btn btn-popell">Aanmaken</button>
    </form>
{% endblock %}

core/templates/add_custom_song_success.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}{{ hitlist.name }}{% endblock %}
{% block content %}
    <h1>Je nummer is toegevoegd!</h1>
    <p>Je kunt nu deze pagina sluiten.</p>
    <a class="btn btn-popell" href="javascript:close()">Sluit pagina</a>
{% endblock %}

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Top 100{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">


    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/logo.css' %}" rel="stylesheet">
    {% if hitlist and hitlist.theme == 'carnaval' %}
        <link href="{% static 'css/carnaval.css' %}" rel="stylesheet">
    {% endif %}
    {% block head %} {% endblock %}
</head>
<body>
<div class="col-lg-10 mx-auto pt-4 py-md-5">
    <header class="pb-3 mb-4 border-bottom">
        <div class="logo">
            <span class="logo_stichting">STICHTING</span>
            <span class="logo_popell">POPELL</span>
        </div>
    </header>
    <div class="content">
        {% block content %}<!-- default content text (typically empty) -->{% endblock %}
    </div>
    <footer class="py-3 mt-4 border-top footer bottom">
        <p class="text-center">Bij elkaar gecomputerd door <a href="https://github.com/jur-clerkx/">@jur-clerkx</a>
            & <a href="https://github.com/KaiCorstjens/">@KaiCorstjens</a></p>
    </footer>
</div>
</body>
</html>

core/templates/closed.html
{% extends 'base.html' %}
{% block content %}
    <h1>De lijst is gesloten</h1>
    <p>Helaas is het niet mogelijk om op dit moment te stemmen. De lijst is al gesloten.</p>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% block title %}{{ hitlist.name }}{% endblock %}
{% block content %}
    <h1>{{ hitlist.name }}</h1>
    {{ hitlist.description | safe }}
    <a href="{% url 'core:vote' %}" class="btn btn-popell">Open stem formulier</a>
{% endblock %}

core/templates/view_vote_submission.html
{% extends "base.html" %}
{% load static %}
{% load core_extras %}

{% block head %}
    <link href="{% static 'css/vote_submission.css' %}" rel="stylesheet">
    <meta property="og:url" content="{{ request.path }}"/>
    <meta property="og:title" content="Mijn {{ object.hit_list.name }} Inzending"/>
    <meta property="og:description" content="Bekijk de inzending van {{ object.submitter_name }}!"/>
    {% if hitlist.theme == 'rock' %}
        <meta property="og:image" content="{% static 'img/popell_background.jpg' %}"/>
    {% elif hitlist.theme == 'carnaval' %}
        <meta property="og:image" content="{% static 'img/carnaval-background.jpg' %}"/>
    {% endif %}
{% endblock %}


{% block title %}{{ object.hit_list.name }}{% endblock %}

{% block content %}
    <!-- Facebook javascript SDK-->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/nl_NL/sdk.js#xfbml=1&version=v15.0"
            nonce="4R8VAr9R"></script>
    <h2 class="py-4 border-bottom">Inzending van {{ object.submitter_name }} voor {{ object.hit_list.name }}</h2>
    <div class="fb-share-button" data-href="{{ request.path }}" data-layout="button"
         data-size="large"><a target="_blank"
                              href="https://www.facebook.com/sharer/sharer.php?u={{ request.path|urlencode }}&amp;src=sdkpreparse"
                              class="fb-xfbml-parse-ignore">Delen</a></div>
    <div class="vote_submission_container">
        <h4>Nummer 1 (5 punten):</h4>
        <div class="vote_container pb-4">
            <img class="vote_track_image" src="{{ object.vote_set.all.0.track.image_url }}"
                 alt="{{ object.vote_set.all.0.track.title }}"/>
            <div>
                <p class="vote_track_name">{{ object.vote_set.all.0.track.title }}</p>
                <p class="vote_artist">{{ object.vote_set.all.0.track.artists.all | artist_list }}</p>
            </div>
            <audio class="vote_track_preview" controls>
                <source src="{{ object.vote_set.all.0.track.preview_url }}">
            </audio>
        </div>
        <h4>Nummer 2 (4 punten):</h4>
        <div class="vote_container pb-4">
            <img class="vote_track_image" src="{{ object.vote_set.all.1.track.image_url }}"
                 alt="{{ object.vote_set.all.1.track.title }}"/>
            <div>
                <p class="vote_track_name">{{ object.vote_set.all.1.track.title }}</p>
                <p class="vote_artist">{{ object.vote_set.all.1.track.artists.all | artist_list }}</p>
            </div>
            <audio class="vote_track_preview" controls>
                <source src="{{ object.vote_set.all.1.track.preview_url }}">
            </audio>
        </div>
        <h4>Nummer 3 (3 punten):</h4>
        <div class="vote_container pb-4">
            <img class="vote_track_image" src="{{ object.vote_set.all.2.track.image_url }}"
                 alt="{{ object.vote_set.all.2.track.title }}"/>
            <div>
                <p class="vote_track_name">{{ object.vote_set.all.2.track.title }}</p>
                <p class="vote_artist">{{ object.vote_set.all.2.track.artists.all | artist_list }}</p>
            </div>
            <audio class="vote_track_preview" controls>
                <source src="{{ object.vote_set.all.2.track.preview_url }}">
            </audio>
        </div>
        <h4>Nummer 4 (2 punten):</h4>
        <div class="vote_container pb-4">
            <img class="vote_track_image" src="{{ object.vote_set.all.3.track.image_url }}"
                 alt="{{ object.vote_set.all.3.track.title }}"/>
            <div>
                <p class="vote_track_name">{{ object.vote_set.all.3.track.title }}</p>
                <p class="vote_artist">{{ object.vote_set.all.3.track.artists.all | artist_list }}</p>
            </div>
            <audio class="vote_track_preview" controls>
                <source src="{{ object.vote_set.all.3.track.preview_url }}">
            </audio>
        </div>
        <h4>Nummer 5 (1 punt):</h4>
        <div class="vote_container pb-4">
            <img class="vote_track_image" src="{{ object.vote_set.all.4.track.image_url }}"
                 alt="{{ object.vote_set.all.4.track.title }}"/>
            <div>
                <p class="vote_track_name">{{ object.vote_set.all.4.track.title }}</p>
                <p class="vote_artist">{{ object.vote_set.all.4.track.artists.all | artist_list }}</p>
            </div>
            <audio class="vote_track_preview" controls>
                <source src="{{ object.vote_set.all.4.track.preview_url }}">
            </audio>
        </div>
    </div>
{% endblock %}

core/templates/vote.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ hitlist.name }}{% endblock %}

{% block head %}
    <link href="{% static 'css/vote.css' %}" rel="stylesheet">
    {# Load jQuery #}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    {# Load Select2 #}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/nl.js"></script>

    <script>
        function formatStateResult(state) {
            if (!state.id) { // Select2 internal message (e.g. "Searching...")
                return state.text;
            }
            return $(
                '<div class="selection_result_container">' +
                '<img src="' + state.image + '" class="selection_result_image"/>' +
                '<div>' +
                '<p class="selection_result_track_name">' + state.track_name + '</p>' +
                '<p class="selection_result_track_artist">' + state.track_artists.map(function (artist) {
                    return artist.name
                }).join(', ') + '</p>' +
                '</div>' +
                '</div>'
            )
        }

        function formatStateSelection(state) {
            if (!state.id) {  // Select2 internal message (e.g. "Searching...")
                return state.text;
            }
            if (state.id && !state.track_name) { // Initial item of which metadata hasn't been loaded yet.
                console.log("update");
                let xhr = new XMLHttpRequest();
                xhr.open("GET", '/api/get/' + encodeURIComponent(state.id), false)
                xhr.send(null);
                state = JSON.parse(xhr.response);

            }

            return $(
                '<div class="selection_container">' +
                '<img src="' + state.image + '" class="selection_image"/>' +
                '<div>' +
                '<p class="selection_track_name">' + state.track_name + '</p>' +
                '<p class="selection_track_artist">' + state.track_artists.map(function (artist) {
                    return artist.name
                }).join(', ') + '</p>' +
                '</div>' +
                '</div>'
            )
        }

        $(document).ready(function () {
            $('.select_song').select2({
                placeholder: 'Kies een nummer',
                minimumInputLength: 1,
                width: 'resolve',
                "language": "nl",
                ajax: {
                    delay: 250,
                    url: '{% url 'api:search' %}',
                    data: function (params) {
                        return {
                            q: params.term,
                        };
                    }
                },
                templateResult: formatStateResult,
                templateSelection: formatStateSelection,
            });
        });
    </script>
{% endblock %}

{% block content %}
    <h2>{{ hitlist.name }} stemformulier</h2>
    <br/>
    <form method="post">
        {% csrf_token %}
        <label for="name">Naam:</label>
        {{ voteForm.name.errors }}
        <input type="text" name="name" id="name"
               value="{% if voteForm.name.value %}{{ voteForm.name.value }}{% endif %}" placeholder="Pietje puk">

        <p class="my-2">Wij zoeken nummers op spotify. Staat het nummer waar je op wilt stemmen er niet tussen? Druk
            dan op de knop aan de onderkant van de pagina om een eigen nummer toe te voegen.</p>
        <div class="my-4">
            {{ voteForm.non_field_errors }}
            <div class="my-4 song_input">
                <label for="song_1">Nummer 1 (5 punten):</label>
                {{ voteForm.song_1.errors }}
                <select class="select_song" name="song_1" id="song_1">
                    {% if voteForm.song_1.value %}
                        <option value="{{ voteForm.song_1.value }}" selected>init</option>
                    {% endif %}
                </select>
            </div>
            <div class="my-4 song_input">
                <label for="song_2">Nummer 2 (4 punten):</label>
                {{ voteForm.song_2.errors }}
                <select class="select_song" name="song_2" id="song_2">
                    {% if voteForm.song_2.value %}
                        <option value="{{ voteForm.song_2.value }}" selected>init</option>
                    {% endif %}
                </select>
            </div>
            <div class="my-4 song_input">
                <label for="song_3">Nummer 3 (3 punten):</label>
                {{ voteForm.song_3.errors }}
                <select class="select_song" name="song_3" id="song_3">
                    {% if voteForm.song_3.value %}
                        <option value="{{ voteForm.song_3.value }}" selected>init</option>
                    {% endif %}
                </select>
            </div>
            <div class="my-4 song_input">
                <label for="song_4">Nummer 4 (2 punten):</label>
                {{ voteForm.song_4.errors }}
                <select class="select_song" name="song_4" id="song_4">
                    {% if voteForm.song_4.value %}
                        <option value="{{ voteForm.song_4.value }}" selected>init</option>
                    {% endif %}
                </select>
            </div>
            <div class="my-4 song_input">
                <label for="song_5">Nummer 5 (1 punten):</label>
                {{ voteForm.song_5.errors }}
                <select class="select_song" name="song_5" id="song_5">
                    {% if voteForm.song_5.value %}
                        <option value="{{ voteForm.song_5.value }}" selected>init</option>
                    {% endif %}
                </select>
            </div>
        </div>
        <input type="submit" class="btn btn-popell me-2 mb-2">
        <a class="btn btn-popell" href="{% url 'core:add-custom-track' %}" target="_blank">Eigen nummer toevoegen</a>
    </form>
{% endblock %}