core/rest_api/urls.py
from django.urls import path, include
from rest_framework import routers

import core.rest_api.views as views

router = routers.SimpleRouter()

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
    path(
        "current_hitlist/",
        views.CurrentHitListView.as_view(),
        name="current-hitlist",
    ),
    path("api/search/", views.SpotipySearchView.as_view(), name="search"),
    path(
        "api/get/<str:spotifyuri>",
        views.SpotipyGetView.as_view(),
        name="get",
    ),
    path("api/stats/", views.TrackStatsGetView.as_view(), name="track-stats"),
]

core/urls.py
from django.urls import path


import core.views.dashboard as dashboard_views
import core.views.voting as voting_views


app_name = "core"
urlpatterns = [
    path("", voting_views.IndexView.as_view(), name="index"),
    path("closed/", voting_views.HitlistClosedView.as_view(), name="closed"),
    path("stemmen/", voting_views.VoteView.as_view(), name="vote"),
    path(
        "stem/<uuid:pk>",
        voting_views.VoteSubmissionDetailView.as_view(),
        name="vote-submission-detail",
    ),
    path(
        "eigen-nummer-toegevoegen/",
        voting_views.AddCustomTrackView.as_view(),
        name="add-custom-track",
    ),
    path(
        "eigen-nummer-is-toegevoegd/",
        voting_views.AddCustomTrackSuccessView.as_view(),
        name="add-custom-track-success",
    ),
    path(
        "dashboard/", dashboard_views.DashboardView.as_view(), name="dashboard"
    ),
    path(
        "dashboard/cms/hitlist",
        dashboard_views.HistListListView.as_view(),
        name="hitlist-list",
    ),
    path(
        "dashboard/cms/hitlist/create",
        dashboard_views.HitListCreateView.as_view(),
        name="hitlist-create",
    ),
    path(
        "dashboard/cms/hitlist/update/<str:pk>",
        dashboard_views.HitListUpdateView.as_view(),
        name="hitlist-update",
    ),
    path(
        "dashboard/cms/hitlist/delete/<str:pk>",
        dashboard_views.HitListDeleteView.as_view(),
        name="hitlist-delete",
    ),
    path(
        "dashboard/cms/hitlist/export/<str:pk>",
        dashboard_views.HitListExportView.as_view(),
        name="hitlist-export",
    ),
    path(
        "dashboard/cms/similar-tracks",
        dashboard_views.SimilarTrackView.as_view(),
        name="similar-track-list",
    ),
    path(
        "dashboard/cms/custom-track",
        dashboard_views.CustomTrackListView.as_view(),
        name="custom-track-list",
    ),
    path(
        "dashboard/cms/custom-track/update/<str:pk>",
        dashboard_views.CustomTrackUpdateView.as_view(),
        name="custom-track-update",
    ),
    path(
        "dashboard/cms/merge-tracks",
        dashboard_views.MergeTracksView.as_view(),
        name="merge-tracks",
    ),
    path(
        "dashboard/cms/toggle-submission-invalidation/<str:votesubmissionid>",
        dashboard_views.ToggleSubmissionInvalidation.as_view(),
        name="toggle-submission-invalidation",
    ),
    path(
        "dashboard/create-spotify-playlist/<str:hitlist_id>",
        dashboard_views.HitListCreateSpotifyPlaylistView.as_view(),
        name="create-spotify-playlist",
    ),
    path(
        "dashboard/spotify-oauth",
        dashboard_views.SpotifyOAuthView.as_view(),
        name="spotify-oauth",
    ),
]

popell_top100/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("api/", include("core.rest_api.urls")),
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("accounts/login/", LoginView.as_view()),
]

core/models/voting.py
import datetime
import uuid

from django.db import models
from django.db.models import Count, Sum, Min

from core.models.music import Track


class HitList(models.Model):
    THEME_CHOICES = (("rock", "Rock"), ("carnaval", "Carnaval"))

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(
        max_length=255, blank=False, null=False, unique=True
    )
    vote_start_date = models.DateTimeField(blank=False, null=False)
    vote_end_date = models.DateTimeField(blank=False, null=False)
    is_closed = models.BooleanField(default=False)
    description = models.TextField(blank=False, null=False, default="")
    theme = models.CharField(
        max_length=255, choices=THEME_CHOICES, default="rock"
    )

    def get_list(self):
        return (
            Track.objects.filter(
                vote__submission__hit_list=self,
                vote__submission__is_invalidated=False,
            )
            .annotate(
                votes=Count("vote__points"),
                score=Sum("vote__points"),
                first_vote=Min("vote__submission__timestamp"),
            )
            .order_by("-score", "-votes", "first_vote")
            .prefetch_related("artists")
        )


class VoteSubmission(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    submitter_name = models.CharField(max_length=255, blank=False, null=False)
    is_invalidated = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    hit_list = models.ForeignKey(
        HitList, blank=False, null=False, on_delete=models.PROTECT
    )

    def __str__(self):
        return self.submitter_name


class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    track = models.ForeignKey(
        Track, blank=False, null=False, on_delete=models.PROTECT
    )
    submission = models.ForeignKey(
        VoteSubmission, blank=False, null=False, on_delete=models.CASCADE
    )
    points = models.PositiveIntegerField(blank=False, null=False)

core/rest_api/views.py
from rest_framework import generics
from dataclasses import asdict

from core.models.music import Track
from core.models.voting import HitList, Vote, VoteSubmission
from core.rest_api.serializers import HitListSerializer
from core.services.settings import SettingsService
from rest_framework.views import APIView
from rest_framework.response import Response

from core.services.voting import HitListService
from core.spotify import spotify
from rest_framework import status
from rest_framework import permissions


class CurrentHitListView(generics.RetrieveAPIView):
    serializer_class = HitListSerializer

    def get_object(self):
        return SettingsService.get_current_hitlist(self.request)

    def get_queryset(self):
        return HitList.objects.all()


class SpotipySearchView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        q = request.GET.get("q")
        search_results = spotify.search_custom_tracks(
            q
        ) + spotify.search_tracks(q)
        return Response({"results": [asdict(x) for x in search_results]})


class SpotipyGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, spotifyuri, format=None):
        return Response(asdict(spotify.get_track_by_uri(spotifyuri)))


class TrackStatsGetView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, format=None):
        title = request.GET.get("title", "")
        year = request.GET.get("year", "")
        artist = request.GET.get("artist", "")
        track_uri = request.GET.get("spotify_uri", "")
        print(title, year, artist, track_uri)
        hitlist = HitListService.get_by_year(year)
        track = Track.find_by_uri_or_title(track_uri, title)
        if track is None:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not found!"},
            )
        votes = Vote.objects.filter(
            track=track,
            submission__hit_list=hitlist,
            submission__is_invalidated=False,
        )
        if votes.count() == 0:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={"error": "Track not part of hitlist!"},
            )
        position = 1
        for entry in hitlist.get_list():
            if entry.id == track.id:
                break
            position += 1
        vote_count, points = 0, 0
        for vote in votes:
            vote_count += 1
            points += vote.points
        votes = VoteSubmission.objects.filter(
            hit_list=hitlist, vote__track=track, is_invalidated=False
        ).values("submitter_name")
        return Response(
            {
                "track": str(track),
                "position": position,
                "points": points,
                "number_of_votes": vote_count,
                "voters": list(votes),
            }
        )

core/views/dashboard.py
import logging
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    FormView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from core.forms import MergeTracksForm
from core.models.music import Track
from core.models.voting import HitList, VoteSubmission
from core.services.music import SimilarTrackService
from core.services.settings import SettingsService
from core.services.voting import HitListService
from core.spotify import spotify
from core.widgets import CustomDateTimeInput
from tinymce.widgets import TinyMCE  # type: ignore

HITLIST_LIST_URL = "core:hitlist-list"
DASHBOARD_URL = "core:dashboard"


logger = logging.getLogger(__name__)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        if "list" in request.GET:
            hitlist = get_object_or_404(HitList, id=request.GET["list"])
            SettingsService.set_current_hitlist(request, hitlist)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["hitlists"] = HitList.objects.all()
        ctx["hitlist"] = SettingsService.get_current_hitlist(self.request)
        ctx["vote_count"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=False
        ).count()
        ctx["invalidated"] = VoteSubmission.objects.filter(
            hit_list=ctx["hitlist"], is_invalidated=True
        ).count()
        return ctx


class HistListListView(LoginRequiredMixin, ListView):
    model = HitList
    template_name = "dashboard/cms/hitlistlist.html"


class SimilarTrackView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/cms/similartracks.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["similar_tracks"] = SimilarTrackService.get_similar_tracks()
        return ctx


class HitListCreateView(LoginRequiredMixin, CreateView):
    model = HitList
    template_name = "dashboard/cms/hitlistcreate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListUpdateView(LoginRequiredMixin, UpdateView):
    model = HitList
    template_name = "dashboard/cms/hitlistupdate.html"
    fields = [
        "name",
        "vote_start_date",
        "vote_end_date",
        "description",
        "theme",
        "is_closed",
    ]
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["vote_start_date"].widget = CustomDateTimeInput()
        form.fields["vote_end_date"].widget = CustomDateTimeInput()
        form.fields["description"].widget = TinyMCE()
        return form


class HitListDeleteView(LoginRequiredMixin, DeleteView):
    model = HitList
    success_url = reverse_lazy(HITLIST_LIST_URL)
    template_name = "dashboard/cms/hitlistdelete.html"


class HitListExportView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=pk)
        return HitListService.export_to_excel(hitlist)


class CustomTrackListView(LoginRequiredMixin, ListView):
    model = Track
    template_name = "dashboard/cms/tracklist.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_related("artists")
            .filter(is_non_spotify=True)
        )


class CustomTrackUpdateView(LoginRequiredMixin, UpdateView):
    model = Track
    template_name = "dashboard/cms/trackupdate.html"
    fields = ["title", "artists", "preview_url", "image_url"]
    success_url = reverse_lazy("core:custom-track-list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["artists"].queryset = form.fields[
            "artists"
        ].queryset.filter(is_non_spotify=True)
        return form


class MergeTracksView(LoginRequiredMixin, FormView):
    form_class = MergeTracksForm
    template_name = "dashboard/cms/mergetracks.html"
    success_url = reverse_lazy(HITLIST_LIST_URL)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ToggleSubmissionInvalidation(LoginRequiredMixin, View):
    def get(self, request, votesubmissionid, *args, **kwargs):
        submission = VoteSubmission.objects.get(id=votesubmissionid)
        submission.is_invalidated = not submission.is_invalidated
        submission.save()
        return redirect(reverse_lazy(DASHBOARD_URL))


class HitListCreateSpotifyPlaylistView(View):
    def get(self, request, hitlist_id, *args, **kwargs):
        hitlist = get_object_or_404(HitList, id=hitlist_id)
        try:
            HitListService.create_spotify_list(
                hitlist, request.session.get("spotify_token")
            )
        except Exception as e:
            logger.error("Failed to create spotify playlist!")
            logger.error(e)
            request.session["spotify_token"] = None
        return redirect(reverse_lazy(DASHBOARD_URL))


class SpotifyOAuthView(View):
    def get(self, request):
        spotify_oauth = spotify.get_spotify_oauth()
        callback_code = request.GET.get("code", None)
        if callback_code:
            # Found callback code, add access token to session
            access_token = spotify_oauth.get_access_token(callback_code)[
                "access_token"
            ]
            request.session["spotify_token"] = access_token
            return redirect(reverse_lazy(DASHBOARD_URL))
        else:
            return redirect(spotify_oauth.get_authorize_url())

core/views/mixins.py
from django.shortcuts import redirect
from django.views import View

from core.services.voting import HitListService


class OpenHitListRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if (
            not HitListService.get_current_hitlist()
            or HitListService.get_current_hitlist().is_closed
        ):
            return redirect("core:closed")
        return super().dispatch(request, *args, **kwargs)

core/templates/dashboard/base.html
{% load static %}
<!doctype html>
<!--
* Tabler - Premium and Open Source dashboard template with responsive and high quality UI.
* @version 1.0.0-beta5
* @link https://tabler.io
* Copyright 2018-2022 The Tabler Authors
* Copyright 2018-2022 codecalm.net Paweł Kuna
* Licensed under MIT (https://github.com/tabler/tabler/blob/master/LICENSE)
-->
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Top 100 dashboard</title>
    <!-- CSS files -->
    <link href="{% static 'css/dashboard/tabler.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/dashboard/tabler-vendors.min.css' %}" rel="stylesheet"/>
    {% block head %}
    {% endblock %}
</head>
<body class="theme-dark">
<div class="wrapper">
    <header class="navbar navbar-expand-md navbar-dark d-print-none">
        <div class="container-xl">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
                <a href=".">
                    <img src="{% static 'logo.svg' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image">
                </a>
            </h1>
        </div>
    </header>
    <div class="navbar-expand-md">
        <div class="collapse navbar-collapse" id="navbar-menu">
            <div class="navbar navbar-dark">
                <div class="container-xl">
                    <ul class="navbar-nav">
                        {% url 'core:dashboard' as dashboard_link %}
                        <li class="nav-item{% if request.path == dashboard_link %} active{% endif %}">
                            <a class="nav-link" href="{{ dashboard_link }}">
                                <span class="nav-link-title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown{% if 'dashboard/cms' in request.path %} active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"
                               data-bs-auto-close="outside" role="button" aria-expanded="false">
                                <span class="nav-link-title">CMS</span>
                            </a>
                            <div class="dropdown-menu">
                                {% url 'core:hitlist-list' as hitlist_link %}
                                <a class="dropdown-item{% if request.path == hitlist_link %} active{% endif %}"
                                   href="{{ hitlist_link }}">
                                    Top 100 lijsten
                                </a>
                                {% url 'core:custom-track-list' as customtracklist_link %}
                                <a class="dropdown-item{% if request.path == customtracklist_link %} active{% endif %}"
                                   href="{{ customtracklist_link }}">
                                    Eigen nummers
                                </a>
                                {% url 'core:similar-track-list' as similartracklist_link %}
                                <a class="dropdown-item{% if request.path == similartracklist_link %} active{% endif %}"
                                   href="{{ similartracklist_link }}">
                                    Dubbellen nummers
                                </a>
                                {% url 'core:merge-tracks' as mergetracks_link %}
                                <a class="dropdown-item{% if request.path == mergetracks_link %} active{% endif %}"
                                   href="{{ mergetracks_link }}">
                                    Nummers samenvoegen
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="page-wrapper page-dark">
        <div class="container-xl">
            <!-- Page title -->
            <div class="page-header d-print-none">
                <div class="row align-items-center">
                    <div class="col">
                        <h2 class="page-title">
                            {% block title %}{% endblock %}
                        </h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-body">
            <div class="container-xl">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
<!-- Libs JS -->
<!-- Tabler Core -->
<script src="{% static 'js/dashboard/tabler.min.js' %}"></script>
</body>
</html>

core/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load core_extras %}
{% block title %}
    <h1>Dashboard</h1>
{% endblock %}

{% block head %}
    <script>
        function changeHitlist() {
            window.location.href = "?list=" + document.getElementById("hitlistSelect").value;
        }
    </script>
{% endblock %}

{% block content %}
    <label for="hitlistSelect">
        <p>Selecteer lijst voor overzicht:</p>
    </label>
    {% if request.session.spotify_token and hitlist %}
        <a href="{% url 'core:create-spotify-playlist' hitlist.id %}" class="btn btn-primary">
            Maak spotify afspeellijst
        </a>
    {% else %}
        <a href="{% url 'core:spotify-oauth' %}" class="btn btn-primary">
            Authenticate spotify
        </a>
    {% endif %}
    <select class="form-select" id="hitlistSelect" onchange="changeHitlist()">
        {% for item in hitlists %}
            <option{% if item == hitlist %} selected{% endif %} value="{{ item.id }}">{{ item.name }}</option>
        {% endfor %}
    </select>
    <div class="card mt-4">
        <div class="card-header">
            <h4>Tussenstand voor {{ hitlist.name }}</h4>
        </div>
        <div class="table-responsive">
            <table class="table card-table table-vcenter text-nowrap datatable">
                <caption>Tussenstand voor {{ hitlist.name }}</caption>
                <tr>
                    <th>#</th>
                    <th>Titel</th>
                    <th>Artiest</th>
                    <th>Punten</th>
                    <th>Stemmen</th>
                </tr>
                {% for track in hitlist.get_list %}
                    <tr{% if track.is_non_spotify %} class="bg-danger-lt"{% endif %}>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ track.title }}</td>
                        <td>{{ track.artists.all | artist_list }}</td>
                        <td>{{ track.score }}</td>
                        <td>{{ track.votes }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">
                            <h3>Nog geen stemmen binnen</h3>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-header">
            <h4>Stemmen voor {{ hitlist.name }} ({{ vote_count }} geldige stemmen, {{ invalidated }} ongeldig)</h4>
        </div>
        <div class="table-responsive">
            <table class="table card-table table-vcenter text-nowrap datatable">
                <caption>Alle stemmen voor deze top 100 lijst</caption>
                <tr>
                    <th>Ongeldig?</th>
                    <th>Door</th>
                    <th>Tijd</th>
                    <th>#1</th>
                    <th>#2</th>
                    <th>#3</th>
                    <th>#4</th>
                    <th>#5</th>
                </tr>
                {% for vote in hitlist.votesubmission_set.all|dictsortreversed:"timestamp" %}
                    {% with vote.vote_set.all as votes %}
                        <tr>
                            <td>
                                <a href="{% url 'core:toggle-submission-invalidation' vote.id %}">
                                    {{ vote.is_invalidated|yesno:"Ja,Nee" }}
                                </a>
                            </td>
                            <td>{{ vote.submitter_name }}</td>
                            <td>{{ vote.timestamp }}</td>
                            <td>{{ votes.0.track }}</td>
                            <td>{{ votes.1.track }}</td>
                            <td>{{ votes.2.track }}</td>
                            <td>{{ votes.3.track }}</td>
                            <td>{{ votes.4.track }}</td>
                        </tr>
                    {% endwith %}
                {% empty %}
                    <tr>
                        <td colspan="8">
                            <h3>Nog geen stemmen binnen</h3>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-header">
            <h4>Stem namen</h4>
        </div>
        <div class="table-responsive">
            <table class="table card-table table-vcenter text-nowrap datatable">
                <caption>Lijst van namen van de mensen die gestemd hebben</caption>
                <tr>
                    <th>Naam</th>
                </tr>
                {% for vote in hitlist.votesubmission_set.all %}
                    {% if not vote.is_invalidated %}
                        <tr>
                            <td>{{ vote.submitter_name }}</td>
                        </tr>
                    {% endif %}
                {% empty %}
                    <tr>
                        <td colspan="8">
                            <h3>Nog geen stemmen binnen</h3>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}